jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install dependencies
        run: npm ci

      - name: Verify tsconfig.json exists
        run: ls -la tsconfig.json

      - name: Run Cypress tests with ts-node support
        run: npx ts-node --transpile-only node_modules/.bin/cypress run
      
      - name: Run Cypress tests
        run: npx cypress run